// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	AccountId            int64                  `protobuf:"varint,5,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CategoryId           string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PublishStatus        string                 `protobuf:"bytes,7,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	ModerationStatus     string                 `protobuf:"bytes,8,opt,name=moderation_status,json=moderationStatus,proto3" json:"moderation_status,omitempty"`
	ModerationReason     string                 `protobuf:"bytes,9,opt,name=moderation_reason,json=moderationReason,proto3" json:"moderation_reason,omitempty"`
	Media                []*ProductMedia        `protobuf:"bytes,10,rep,name=media,proto3" json:"media,omitempty"`
	DiscountPercentage   float64                `protobuf:"fixed64,11,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	Rating               float64                `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	Stock                int32                  `protobuf:"varint,13,opt,name=stock,proto3" json:"stock,omitempty"`
	Tags                 []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Brand                string                 `protobuf:"bytes,15,opt,name=brand,proto3" json:"brand,omitempty"`
	Sku                  string                 `protobuf:"bytes,16,opt,name=sku,proto3" json:"sku,omitempty"`
	Weight               float64                `protobuf:"fixed64,17,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions           *ProductDimensions     `protobuf:"bytes,18,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	WarrantyInformation  string                 `protobuf:"bytes,19,opt,name=warranty_information,json=warrantyInformation,proto3" json:"warranty_information,omitempty"`
	ShippingInformation  string                 `protobuf:"bytes,20,opt,name=shipping_information,json=shippingInformation,proto3" json:"shipping_information,omitempty"`
	AvailabilityStatus   string                 `protobuf:"bytes,21,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	Reviews              []*ProductReview       `protobuf:"bytes,22,rep,name=reviews,proto3" json:"reviews,omitempty"`
	ReturnPolicy         string                 `protobuf:"bytes,23,opt,name=return_policy,json=returnPolicy,proto3" json:"return_policy,omitempty"`
	MinimumOrderQuantity int32                  `protobuf:"varint,24,opt,name=minimum_order_quantity,json=minimumOrderQuantity,proto3" json:"minimum_order_quantity,omitempty"`
	Meta                 *ProductMeta           `protobuf:"bytes,25,opt,name=meta,proto3" json:"meta,omitempty"`
	Thumbnail            string                 `protobuf:"bytes,26,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Images               []string               `protobuf:"bytes,27,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetPublishStatus() string {
	if x != nil {
		return x.PublishStatus
	}
	return ""
}

func (x *Product) GetModerationStatus() string {
	if x != nil {
		return x.ModerationStatus
	}
	return ""
}

func (x *Product) GetModerationReason() string {
	if x != nil {
		return x.ModerationReason
	}
	return ""
}

func (x *Product) GetMedia() []*ProductMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Product) GetDiscountPercentage() float64 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

func (x *Product) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Product) GetDimensions() *ProductDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Product) GetWarrantyInformation() string {
	if x != nil {
		return x.WarrantyInformation
	}
	return ""
}

func (x *Product) GetShippingInformation() string {
	if x != nil {
		return x.ShippingInformation
	}
	return ""
}

func (x *Product) GetAvailabilityStatus() string {
	if x != nil {
		return x.AvailabilityStatus
	}
	return ""
}

func (x *Product) GetReviews() []*ProductReview {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *Product) GetReturnPolicy() string {
	if x != nil {
		return x.ReturnPolicy
	}
	return ""
}

func (x *Product) GetMinimumOrderQuantity() int32 {
	if x != nil {
		return x.MinimumOrderQuantity
	}
	return 0
}

func (x *Product) GetMeta() *ProductMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Product) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type ProductMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMedia) Reset() {
	*x = ProductMedia{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMedia) ProtoMessage() {}

func (x *ProductMedia) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMedia.ProtoReflect.Descriptor instead.
func (*ProductMedia) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductMedia) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductMedia) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductMedia) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *ProductMedia) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ProductDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         float64                `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Depth         float64                `protobuf:"fixed64,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDimensions) Reset() {
	*x = ProductDimensions{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDimensions) ProtoMessage() {}

func (x *ProductDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDimensions.ProtoReflect.Descriptor instead.
func (*ProductDimensions) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductDimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProductDimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProductDimensions) GetDepth() float64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type ProductReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        int32                  `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	ReviewerName  string                 `protobuf:"bytes,4,opt,name=reviewer_name,json=reviewerName,proto3" json:"reviewer_name,omitempty"`
	ReviewerEmail string                 `protobuf:"bytes,5,opt,name=reviewer_email,json=reviewerEmail,proto3" json:"reviewer_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReview) Reset() {
	*x = ProductReview{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReview) ProtoMessage() {}

func (x *ProductReview) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReview.ProtoReflect.Descriptor instead.
func (*ProductReview) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductReview) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductReview) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ProductReview) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ProductReview) GetReviewerName() string {
	if x != nil {
		return x.ReviewerName
	}
	return ""
}

func (x *ProductReview) GetReviewerEmail() string {
	if x != nil {
		return x.ReviewerEmail
	}
	return ""
}

type ProductMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Barcode       string                 `protobuf:"bytes,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
	QrCode        string                 `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMeta) Reset() {
	*x = ProductMeta{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMeta) ProtoMessage() {}

func (x *ProductMeta) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMeta.ProtoReflect.Descriptor instead.
func (*ProductMeta) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductMeta) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductMeta) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProductMeta) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductMeta) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetProductsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetProductsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AdminGetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProductsRequest) Reset() {
	*x = AdminGetProductsRequest{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProductsRequest) ProtoMessage() {}

func (x *AdminGetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProductsRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *AdminGetProductsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *AdminGetProductsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	AccountId     int64                  `protobuf:"varint,5,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeleteProductRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type AddProductReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ReviewerName  string                 `protobuf:"bytes,4,opt,name=reviewer_name,json=reviewerName,proto3" json:"reviewer_name,omitempty"`
	ReviewerEmail string                 `protobuf:"bytes,5,opt,name=reviewer_email,json=reviewerEmail,proto3" json:"reviewer_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductReviewRequest) Reset() {
	*x = AddProductReviewRequest{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductReviewRequest) ProtoMessage() {}

func (x *AddProductReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductReviewRequest.ProtoReflect.Descriptor instead.
func (*AddProductReviewRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *AddProductReviewRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddProductReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddProductReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AddProductReviewRequest) GetReviewerName() string {
	if x != nil {
		return x.ReviewerName
	}
	return ""
}

func (x *AddProductReviewRequest) GetReviewerEmail() string {
	if x != nil {
		return x.ReviewerEmail
	}
	return ""
}

type ProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsResponse) Reset() {
	*x = ProductsResponse{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResponse) ProtoMessage() {}

func (x *ProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResponse.ProtoReflect.Descriptor instead.
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *ProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type AdminProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ActorRole     string                 `protobuf:"bytes,2,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProductRequest) Reset() {
	*x = AdminProductRequest{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProductRequest) ProtoMessage() {}

func (x *AdminProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProductRequest.ProtoReflect.Descriptor instead.
func (*AdminProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *AdminProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *AdminProductRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type AdminDeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActorRole     string                 `protobuf:"bytes,2,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteProductRequest) Reset() {
	*x = AdminDeleteProductRequest{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteProductRequest) ProtoMessage() {}

func (x *AdminDeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteProductRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *AdminDeleteProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AdminDeleteProductRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type ModerateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PublishStatus    string                 `protobuf:"bytes,2,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	ModerationStatus string                 `protobuf:"bytes,3,opt,name=moderation_status,json=moderationStatus,proto3" json:"moderation_status,omitempty"`
	ModerationReason string                 `protobuf:"bytes,4,opt,name=moderation_reason,json=moderationReason,proto3" json:"moderation_reason,omitempty"`
	ActorRole        string                 `protobuf:"bytes,5,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModerateProductRequest) Reset() {
	*x = ModerateProductRequest{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateProductRequest) ProtoMessage() {}

func (x *ModerateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateProductRequest.ProtoReflect.Descriptor instead.
func (*ModerateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *ModerateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ModerateProductRequest) GetPublishStatus() string {
	if x != nil {
		return x.PublishStatus
	}
	return ""
}

func (x *ModerateProductRequest) GetModerationStatus() string {
	if x != nil {
		return x.ModerationStatus
	}
	return ""
}

func (x *ModerateProductRequest) GetModerationReason() string {
	if x != nil {
		return x.ModerationReason
	}
	return ""
}

func (x *ModerateProductRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type AddProductMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Media         *ProductMedia          `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	ActorRole     string                 `protobuf:"bytes,3,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductMediaRequest) Reset() {
	*x = AddProductMediaRequest{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductMediaRequest) ProtoMessage() {}

func (x *AddProductMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductMediaRequest.ProtoReflect.Descriptor instead.
func (*AddProductMediaRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *AddProductMediaRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddProductMediaRequest) GetMedia() *ProductMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *AddProductMediaRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type CategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	ActorRole     string                 `protobuf:"bytes,2,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

func (x *CategoryRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *CategoryRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{19}
}

func (x *ListCategoriesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type CategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoriesResponse) Reset() {
	*x = CategoriesResponse{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesResponse) ProtoMessage() {}

func (x *CategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesResponse.ProtoReflect.Descriptor instead.
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{20}
}

func (x *CategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb1\a\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\taccountId\x18\x05 \x01(\x03R\taccountId\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\x0epublish_status\x18\a \x01(\tR\rpublishStatus\x12+\n" +
	"\x11moderation_status\x18\b \x01(\tR\x10moderationStatus\x12+\n" +
	"\x11moderation_reason\x18\t \x01(\tR\x10moderationReason\x12&\n" +
	"\x05media\x18\n" +
	" \x03(\v2\x10.pb.ProductMediaR\x05media\x12/\n" +
	"\x13discount_percentage\x18\v \x01(\x01R\x12discountPercentage\x12\x16\n" +
	"\x06rating\x18\f \x01(\x01R\x06rating\x12\x14\n" +
	"\x05stock\x18\r \x01(\x05R\x05stock\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x14\n" +
	"\x05brand\x18\x0f \x01(\tR\x05brand\x12\x10\n" +
	"\x03sku\x18\x10 \x01(\tR\x03sku\x12\x16\n" +
	"\x06weight\x18\x11 \x01(\x01R\x06weight\x125\n" +
	"\n" +
	"dimensions\x18\x12 \x01(\v2\x15.pb.ProductDimensionsR\n" +
	"dimensions\x121\n" +
	"\x14warranty_information\x18\x13 \x01(\tR\x13warrantyInformation\x121\n" +
	"\x14shipping_information\x18\x14 \x01(\tR\x13shippingInformation\x12/\n" +
	"\x13availability_status\x18\x15 \x01(\tR\x12availabilityStatus\x12+\n" +
	"\areviews\x18\x16 \x03(\v2\x11.pb.ProductReviewR\areviews\x12#\n" +
	"\rreturn_policy\x18\x17 \x01(\tR\freturnPolicy\x124\n" +
	"\x16minimum_order_quantity\x18\x18 \x01(\x05R\x14minimumOrderQuantity\x12#\n" +
	"\x04meta\x18\x19 \x01(\v2\x0f.pb.ProductMetaR\x04meta\x12\x1c\n" +
	"\tthumbnail\x18\x1a \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06images\x18\x1b \x03(\tR\x06images\"j\n" +
	"\fProductMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"W\n" +
	"\x11ProductDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x01R\x06height\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x01R\x05depth\"\xa1\x01\n" +
	"\rProductReview\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12#\n" +
	"\rreviewer_name\x18\x04 \x01(\tR\freviewerName\x12%\n" +
	"\x0ereviewer_email\x18\x05 \x01(\tR\rreviewerEmail\"~\n" +
	"\vProductMeta\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\abarcode\x18\x03 \x01(\tR\abarcode\x12\x17\n" +
	"\aqr_code\x18\x04 \x01(\tR\x06qrCode\"\x81\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\x80\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1c\n" +
	"\taccountId\x18\x04 \x01(\x03R\taccountId\"\x80\x01\n" +
	"\x12GetProductsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"A\n" +
	"\x17AdminGetProductsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\"\x90\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\taccountId\x18\x05 \x01(\x03R\taccountId\"R\n" +
	"\x14DeleteProductRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\"8\n" +
	"\x0fProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.pb.ProductR\aproduct\"\xb6\x01\n" +
	"\x17AddProductReviewRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12#\n" +
	"\rreviewer_name\x18\x04 \x01(\tR\freviewerName\x12%\n" +
	"\x0ereviewer_email\x18\x05 \x01(\tR\rreviewerEmail\";\n" +
	"\x10ProductsResponse\x12'\n" +
	"\bproducts\x18\x01 \x03(\v2\v.pb.ProductR\bproducts\"[\n" +
	"\x13AdminProductRequest\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.pb.ProductR\aproduct\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x02 \x01(\tR\tactorRole\"Y\n" +
	"\x19AdminDeleteProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x02 \x01(\tR\tactorRole\"\xd7\x01\n" +
	"\x16ModerateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12%\n" +
	"\x0epublish_status\x18\x02 \x01(\tR\rpublishStatus\x12+\n" +
	"\x11moderation_status\x18\x03 \x01(\tR\x10moderationStatus\x12+\n" +
	"\x11moderation_reason\x18\x04 \x01(\tR\x10moderationReason\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x05 \x01(\tR\tactorRole\"~\n" +
	"\x16AddProductMediaRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12&\n" +
	"\x05media\x18\x02 \x01(\v2\x10.pb.ProductMediaR\x05media\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x03 \x01(\tR\tactorRole\"Z\n" +
	"\x0fCategoryRequest\x12(\n" +
	"\bcategory\x18\x01 \x01(\v2\f.pb.CategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x02 \x01(\tR\tactorRole\"8\n" +
	"\x15ListCategoriesRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"B\n" +
	"\x12CategoriesResponse\x12,\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\f.pb.CategoryR\n" +
	"categories2\xef\x06\n" +
	"\x0eProductService\x12<\n" +
	"\vPostProduct\x12\x18.pb.CreateProductRequest\x1a\x13.pb.ProductResponse\x12?\n" +
	"\n" +
	"GetProduct\x12\x1c.google.protobuf.StringValue\x1a\x13.pb.ProductResponse\x12;\n" +
	"\vGetProducts\x12\x16.pb.GetProductsRequest\x1a\x14.pb.ProductsResponse\x12E\n" +
	"\x10AdminGetProducts\x12\x1b.pb.AdminGetProductsRequest\x1a\x14.pb.ProductsResponse\x12>\n" +
	"\rUpdateProduct\x12\x18.pb.UpdateProductRequest\x1a\x13.pb.ProductResponse\x12A\n" +
	"\rDeleteProduct\x12\x18.pb.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x12AdminUpdateProduct\x12\x17.pb.AdminProductRequest\x1a\x13.pb.ProductResponse\x12K\n" +
	"\x12AdminDeleteProduct\x12\x1d.pb.AdminDeleteProductRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0fModerateProduct\x12\x1a.pb.ModerateProductRequest\x1a\x13.pb.ProductResponse\x12B\n" +
	"\x0fAddProductMedia\x12\x1a.pb.AddProductMediaRequest\x1a\x13.pb.ProductResponse\x12D\n" +
	"\x10AddProductReview\x12\x1b.pb.AddProductReviewRequest\x1a\x13.pb.ProductResponse\x123\n" +
	"\x0eCreateCategory\x12\x13.pb.CategoryRequest\x1a\f.pb.Category\x12C\n" +
	"\x0eListCategories\x12\x19.pb.ListCategoriesRequest\x1a\x16.pb.CategoriesResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_product_proto_goTypes = []any{
	(*Product)(nil),                   // 0: pb.Product
	(*ProductMedia)(nil),              // 1: pb.ProductMedia
	(*ProductDimensions)(nil),         // 2: pb.ProductDimensions
	(*ProductReview)(nil),             // 3: pb.ProductReview
	(*ProductMeta)(nil),               // 4: pb.ProductMeta
	(*Category)(nil),                  // 5: pb.Category
	(*CreateProductRequest)(nil),      // 6: pb.CreateProductRequest
	(*GetProductsRequest)(nil),        // 7: pb.GetProductsRequest
	(*AdminGetProductsRequest)(nil),   // 8: pb.AdminGetProductsRequest
	(*UpdateProductRequest)(nil),      // 9: pb.UpdateProductRequest
	(*DeleteProductRequest)(nil),      // 10: pb.DeleteProductRequest
	(*ProductResponse)(nil),           // 11: pb.ProductResponse
	(*AddProductReviewRequest)(nil),   // 12: pb.AddProductReviewRequest
	(*ProductsResponse)(nil),          // 13: pb.ProductsResponse
	(*AdminProductRequest)(nil),       // 14: pb.AdminProductRequest
	(*AdminDeleteProductRequest)(nil), // 15: pb.AdminDeleteProductRequest
	(*ModerateProductRequest)(nil),    // 16: pb.ModerateProductRequest
	(*AddProductMediaRequest)(nil),    // 17: pb.AddProductMediaRequest
	(*CategoryRequest)(nil),           // 18: pb.CategoryRequest
	(*ListCategoriesRequest)(nil),     // 19: pb.ListCategoriesRequest
	(*CategoriesResponse)(nil),        // 20: pb.CategoriesResponse
	(*wrapperspb.StringValue)(nil),    // 21: google.protobuf.StringValue
	(*emptypb.Empty)(nil),             // 22: google.protobuf.Empty
}
var file_product_proto_depIdxs = []int32{
	1,  // 0: pb.Product.media:type_name -> pb.ProductMedia
	2,  // 1: pb.Product.dimensions:type_name -> pb.ProductDimensions
	3,  // 2: pb.Product.reviews:type_name -> pb.ProductReview
	4,  // 3: pb.Product.meta:type_name -> pb.ProductMeta
	0,  // 4: pb.ProductResponse.product:type_name -> pb.Product
	0,  // 5: pb.ProductsResponse.products:type_name -> pb.Product
	0,  // 6: pb.AdminProductRequest.product:type_name -> pb.Product
	1,  // 7: pb.AddProductMediaRequest.media:type_name -> pb.ProductMedia
	5,  // 8: pb.CategoryRequest.category:type_name -> pb.Category
	5,  // 9: pb.CategoriesResponse.categories:type_name -> pb.Category
	6,  // 10: pb.ProductService.PostProduct:input_type -> pb.CreateProductRequest
	21, // 11: pb.ProductService.GetProduct:input_type -> google.protobuf.StringValue
	7,  // 12: pb.ProductService.GetProducts:input_type -> pb.GetProductsRequest
	8,  // 13: pb.ProductService.AdminGetProducts:input_type -> pb.AdminGetProductsRequest
	9,  // 14: pb.ProductService.UpdateProduct:input_type -> pb.UpdateProductRequest
	10, // 15: pb.ProductService.DeleteProduct:input_type -> pb.DeleteProductRequest
	14, // 16: pb.ProductService.AdminUpdateProduct:input_type -> pb.AdminProductRequest
	15, // 17: pb.ProductService.AdminDeleteProduct:input_type -> pb.AdminDeleteProductRequest
	16, // 18: pb.ProductService.ModerateProduct:input_type -> pb.ModerateProductRequest
	17, // 19: pb.ProductService.AddProductMedia:input_type -> pb.AddProductMediaRequest
	12, // 20: pb.ProductService.AddProductReview:input_type -> pb.AddProductReviewRequest
	18, // 21: pb.ProductService.CreateCategory:input_type -> pb.CategoryRequest
	19, // 22: pb.ProductService.ListCategories:input_type -> pb.ListCategoriesRequest
	11, // 23: pb.ProductService.PostProduct:output_type -> pb.ProductResponse
	11, // 24: pb.ProductService.GetProduct:output_type -> pb.ProductResponse
	13, // 25: pb.ProductService.GetProducts:output_type -> pb.ProductsResponse
	13, // 26: pb.ProductService.AdminGetProducts:output_type -> pb.ProductsResponse
	11, // 27: pb.ProductService.UpdateProduct:output_type -> pb.ProductResponse
	22, // 28: pb.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	11, // 29: pb.ProductService.AdminUpdateProduct:output_type -> pb.ProductResponse
	22, // 30: pb.ProductService.AdminDeleteProduct:output_type -> google.protobuf.Empty
	11, // 31: pb.ProductService.ModerateProduct:output_type -> pb.ProductResponse
	11, // 32: pb.ProductService.AddProductMedia:output_type -> pb.ProductResponse
	11, // 33: pb.ProductService.AddProductReview:output_type -> pb.ProductResponse
	5,  // 34: pb.ProductService.CreateCategory:output_type -> pb.Category
	20, // 35: pb.ProductService.ListCategories:output_type -> pb.CategoriesResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
