package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Tuananh165art/GoshopX/graphql/generated"
)

// Orders is the resolver for the orders field.
func (r *accountServer) Orders(ctx context.Context, obj *generated.Account) ([]*generated.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Register is the resolver for the register field.
func (r *mutationServer) Register(ctx context.Context, account generated.RegisterInput) (*generated.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationServer) Login(ctx context.Context, account generated.LoginInput) (*generated.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// LoginWithGoogle is the resolver for the loginWithGoogle field.
func (r *mutationServer) LoginWithGoogle(ctx context.Context, account generated.GoogleLoginInput) (*generated.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: LoginWithGoogle - loginWithGoogle"))
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationServer) RequestPasswordReset(ctx context.Context, email string) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestPasswordReset - requestPasswordReset"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationServer) ResetPassword(ctx context.Context, email string, otp string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationServer) UpdateMyProfile(ctx context.Context, input generated.ProfileInput) (*generated.Account, error) {
	panic(fmt.Errorf("not implemented: UpdateMyProfile - updateMyProfile"))
}

// Logout is the resolver for the logout field.
func (r *mutationServer) Logout(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// RecommendChat is the resolver for the recommendChat field.
func (r *mutationServer) RecommendChat(ctx context.Context, input generated.RecommendationChatInput) (*generated.RecommendationChatResponse, error) {
	panic(fmt.Errorf("not implemented: RecommendChat - recommendChat"))
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationServer) CreateProduct(ctx context.Context, product generated.CreateProductInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationServer) UpdateProduct(ctx context.Context, product generated.UpdateProductInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationServer) DeleteProduct(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationServer) CreateOrder(ctx context.Context, order generated.OrderInput) (*generated.Order, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// CreateCustomerPortalSession is the resolver for the createCustomerPortalSession field.
func (r *mutationServer) CreateCustomerPortalSession(ctx context.Context, credentials *generated.CustomerPortalSessionInput) (*generated.RedirectResponse, error) {
	panic(fmt.Errorf("not implemented: CreateCustomerPortalSession - createCustomerPortalSession"))
}

// CreateCheckoutSession is the resolver for the createCheckoutSession field.
func (r *mutationServer) CreateCheckoutSession(ctx context.Context, details *generated.CheckoutInput) (*generated.RedirectResponse, error) {
	panic(fmt.Errorf("not implemented: CreateCheckoutSession - createCheckoutSession"))
}

// UpsertProductStock is the resolver for the upsertProductStock field.
func (r *mutationServer) UpsertProductStock(ctx context.Context, input generated.UpsertProductStockInput) (*generated.InventoryAvailability, error) {
	panic(fmt.Errorf("not implemented: UpsertProductStock - upsertProductStock"))
}

// AddCartItem is the resolver for the addCartItem field.
func (r *mutationServer) AddCartItem(ctx context.Context, productID string, quantity int) (*generated.Cart, error) {
	panic(fmt.Errorf("not implemented: AddCartItem - addCartItem"))
}

// UpdateCartItemQuantity is the resolver for the updateCartItemQuantity field.
func (r *mutationServer) UpdateCartItemQuantity(ctx context.Context, productID string, quantity int) (*generated.Cart, error) {
	panic(fmt.Errorf("not implemented: UpdateCartItemQuantity - updateCartItemQuantity"))
}

// AddProductReview is the resolver for the addProductReview field.
func (r *mutationServer) AddProductReview(ctx context.Context, productID string, rating int, comment string) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AddProductReview - addProductReview"))
}

// RemoveCartItem is the resolver for the removeCartItem field.
func (r *mutationServer) RemoveCartItem(ctx context.Context, productID string) (*generated.Cart, error) {
	panic(fmt.Errorf("not implemented: RemoveCartItem - removeCartItem"))
}

// ClearCart is the resolver for the clearCart field.
func (r *mutationServer) ClearCart(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: ClearCart - clearCart"))
}

// CheckoutCart is the resolver for the checkoutCart field.
func (r *mutationServer) CheckoutCart(ctx context.Context, redirectURL string) (*generated.RedirectResponse, error) {
	panic(fmt.Errorf("not implemented: CheckoutCart - checkoutCart"))
}

// CheckoutCartCod is the resolver for the checkoutCartCOD field.
func (r *mutationServer) CheckoutCartCod(ctx context.Context) (*generated.CODCheckoutResponse, error) {
	panic(fmt.Errorf("not implemented: CheckoutCartCod - checkoutCartCOD"))
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationServer) MarkNotificationRead(ctx context.Context, id int) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkNotificationRead - markNotificationRead"))
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationServer) MarkAllNotificationsRead(ctx context.Context) (int, error) {
	panic(fmt.Errorf("not implemented: MarkAllNotificationsRead - markAllNotificationsRead"))
}

// SuspendAccount is the resolver for the suspendAccount field.
func (r *mutationServer) SuspendAccount(ctx context.Context, id int) (bool, error) {
	panic(fmt.Errorf("not implemented: SuspendAccount - suspendAccount"))
}

// ReactivateAccount is the resolver for the reactivateAccount field.
func (r *mutationServer) ReactivateAccount(ctx context.Context, id int) (bool, error) {
	panic(fmt.Errorf("not implemented: ReactivateAccount - reactivateAccount"))
}

// SetAccountRole is the resolver for the setAccountRole field.
func (r *mutationServer) SetAccountRole(ctx context.Context, id int, role generated.AccountRole) (*generated.Account, error) {
	panic(fmt.Errorf("not implemented: SetAccountRole - setAccountRole"))
}

// AdminCreateCategory is the resolver for the adminCreateCategory field.
func (r *mutationServer) AdminCreateCategory(ctx context.Context, input generated.CreateCategoryInput) (*generated.Category, error) {
	panic(fmt.Errorf("not implemented: AdminCreateCategory - adminCreateCategory"))
}

// AdminModerateProduct is the resolver for the adminModerateProduct field.
func (r *mutationServer) AdminModerateProduct(ctx context.Context, input generated.ModerateProductInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminModerateProduct - adminModerateProduct"))
}

// AdminAddProductMedia is the resolver for the adminAddProductMedia field.
func (r *mutationServer) AdminAddProductMedia(ctx context.Context, input generated.AddProductMediaInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminAddProductMedia - adminAddProductMedia"))
}

// AdminUploadProductMedia is the resolver for the adminUploadProductMedia field.
func (r *mutationServer) AdminUploadProductMedia(ctx context.Context, productID string, file graphql.Upload, altText string, sortOrder int) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminUploadProductMedia - adminUploadProductMedia"))
}

// AdminCreateProduct is the resolver for the adminCreateProduct field.
func (r *mutationServer) AdminCreateProduct(ctx context.Context, input generated.AdminProductInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminCreateProduct - adminCreateProduct"))
}

// AdminUpdateProduct is the resolver for the adminUpdateProduct field.
func (r *mutationServer) AdminUpdateProduct(ctx context.Context, input generated.AdminProductInput) (*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateProduct - adminUpdateProduct"))
}

// AdminDeleteProduct is the resolver for the adminDeleteProduct field.
func (r *mutationServer) AdminDeleteProduct(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: AdminDeleteProduct - adminDeleteProduct"))
}

// AdminCancelOrder is the resolver for the adminCancelOrder field.
func (r *mutationServer) AdminCancelOrder(ctx context.Context, orderID int, reason string) (*generated.AdminOrder, error) {
	panic(fmt.Errorf("not implemented: AdminCancelOrder - adminCancelOrder"))
}

// AdminRequestRefund is the resolver for the adminRequestRefund field.
func (r *mutationServer) AdminRequestRefund(ctx context.Context, input generated.RefundInput) (*generated.RefundResult, error) {
	panic(fmt.Errorf("not implemented: AdminRequestRefund - adminRequestRefund"))
}

// AdminAdjustInventory is the resolver for the adminAdjustInventory field.
func (r *mutationServer) AdminAdjustInventory(ctx context.Context, input generated.InventoryAdjustmentInput) (*generated.InventoryAvailability, error) {
	panic(fmt.Errorf("not implemented: AdminAdjustInventory - adminAdjustInventory"))
}

// Availability is the resolver for the availability field.
func (r *productServer) Availability(ctx context.Context, obj *generated.Product) (*generated.InventoryAvailability, error) {
	panic(fmt.Errorf("not implemented: Availability - availability"))
}

// Accounts is the resolver for the accounts field.
func (r *queryServer) Accounts(ctx context.Context, pagination *generated.PaginationInput, id *int) ([]*generated.Account, error) {
	panic(fmt.Errorf("not implemented: Accounts - accounts"))
}

// AdminAccounts is the resolver for the adminAccounts field.
func (r *queryServer) AdminAccounts(ctx context.Context, pagination *generated.PaginationInput) ([]*generated.Account, error) {
	panic(fmt.Errorf("not implemented: AdminAccounts - adminAccounts"))
}

// Me is the resolver for the me field.
func (r *queryServer) Me(ctx context.Context) (*generated.Account, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Product is the resolver for the product field.
func (r *queryServer) Product(ctx context.Context, pagination *generated.PaginationInput, query *string, category *string, id *string, viewedProductsIds []*string, byAccountID *bool) ([]*generated.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// AdminProducts is the resolver for the adminProducts field.
func (r *queryServer) AdminProducts(ctx context.Context, pagination *generated.PaginationInput) ([]*generated.Product, error) {
	panic(fmt.Errorf("not implemented: AdminProducts - adminProducts"))
}

// CanReviewProduct is the resolver for the canReviewProduct field.
func (r *queryServer) CanReviewProduct(ctx context.Context, productID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CanReviewProduct - canReviewProduct"))
}

// MyOrders is the resolver for the myOrders field.
func (r *queryServer) MyOrders(ctx context.Context) ([]*generated.Order, error) {
	panic(fmt.Errorf("not implemented: MyOrders - myOrders"))
}

// MyPaymentTransactions is the resolver for the myPaymentTransactions field.
func (r *queryServer) MyPaymentTransactions(ctx context.Context, orderID int) ([]*generated.PaymentTransaction, error) {
	panic(fmt.Errorf("not implemented: MyPaymentTransactions - myPaymentTransactions"))
}

// MyCart is the resolver for the myCart field.
func (r *queryServer) MyCart(ctx context.Context) (*generated.Cart, error) {
	panic(fmt.Errorf("not implemented: MyCart - myCart"))
}

// Notifications is the resolver for the notifications field.
func (r *queryServer) Notifications(ctx context.Context, pagination *generated.PaginationInput) ([]*generated.Notification, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *queryServer) UnreadNotificationCount(ctx context.Context) (int, error) {
	panic(fmt.Errorf("not implemented: UnreadNotificationCount - unreadNotificationCount"))
}

// AdminDashboard is the resolver for the adminDashboard field.
func (r *queryServer) AdminDashboard(ctx context.Context, from time.Time, to time.Time, topProductsLimit *int) (*generated.AdminDashboard, error) {
	panic(fmt.Errorf("not implemented: AdminDashboard - adminDashboard"))
}

// AdminAuditEvents is the resolver for the adminAuditEvents field.
func (r *queryServer) AdminAuditEvents(ctx context.Context, pagination *generated.PaginationInput, actorAccountID *int, action *string, from *time.Time, to *time.Time) ([]*generated.AdminAuditEvent, error) {
	panic(fmt.Errorf("not implemented: AdminAuditEvents - adminAuditEvents"))
}

// Categories is the resolver for the categories field.
func (r *queryServer) Categories(ctx context.Context, activeOnly bool) ([]*generated.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// AdminOrders is the resolver for the adminOrders field.
func (r *queryServer) AdminOrders(ctx context.Context, filter *generated.AdminOrderFilter) ([]*generated.AdminOrder, error) {
	panic(fmt.Errorf("not implemented: AdminOrders - adminOrders"))
}

// AdminOrder is the resolver for the adminOrder field.
func (r *queryServer) AdminOrder(ctx context.Context, id int) (*generated.AdminOrder, error) {
	panic(fmt.Errorf("not implemented: AdminOrder - adminOrder"))
}

// AdminTransactions is the resolver for the adminTransactions field.
func (r *queryServer) AdminTransactions(ctx context.Context, status *string, orderID *int, pagination *generated.PaginationInput) ([]*generated.PaymentTransaction, error) {
	panic(fmt.Errorf("not implemented: AdminTransactions - adminTransactions"))
}

// AdminReconcileTransaction is the resolver for the adminReconcileTransaction field.
func (r *queryServer) AdminReconcileTransaction(ctx context.Context, paymentID string) (*generated.PaymentTransaction, error) {
	panic(fmt.Errorf("not implemented: AdminReconcileTransaction - adminReconcileTransaction"))
}

// AdminLowStock is the resolver for the adminLowStock field.
func (r *queryServer) AdminLowStock(ctx context.Context, limit int) ([]*generated.InventoryAvailability, error) {
	panic(fmt.Errorf("not implemented: AdminLowStock - adminLowStock"))
}

// AdminReservations is the resolver for the adminReservations field.
func (r *queryServer) AdminReservations(ctx context.Context, status *string, pagination *generated.PaginationInput) ([]*generated.StockReservation, error) {
	panic(fmt.Errorf("not implemented: AdminReservations - adminReservations"))
}

type accountServer struct{ *Server }
type mutationServer struct{ *Server }
type productServer struct{ *Server }
type queryServer struct{ *Server }
