// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: payment/proto/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutCartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutCartItem) Reset() {
	*x = CheckoutCartItem{}
	mi := &file_payment_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutCartItem) ProtoMessage() {}

func (x *CheckoutCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutCartItem.ProtoReflect.Descriptor instead.
func (*CheckoutCartItem) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutCartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CheckoutCartItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckoutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RedirectURL    string                 `protobuf:"bytes,4,opt,name=redirectURL,proto3" json:"redirectURL,omitempty"`
	Products       []*CheckoutCartItem    `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	OrderId        uint64                 `protobuf:"varint,6,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ReservationIds []string               `protobuf:"bytes,7,rep,name=reservationIds,proto3" json:"reservationIds,omitempty"`
	ClientIp       string                 `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_payment_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckoutRequest) GetRedirectURL() string {
	if x != nil {
		return x.RedirectURL
	}
	return ""
}

func (x *CheckoutRequest) GetProducts() []*CheckoutCartItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *CheckoutRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CheckoutRequest) GetReservationIds() []string {
	if x != nil {
		return x.ReservationIds
	}
	return nil
}

func (x *CheckoutRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type CustomerPortalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerPortalRequest) Reset() {
	*x = CustomerPortalRequest{}
	mi := &file_payment_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerPortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerPortalRequest) ProtoMessage() {}

func (x *CustomerPortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerPortalRequest.ProtoReflect.Descriptor instead.
func (*CustomerPortalRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerPortalRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CustomerPortalRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CustomerPortalRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	SettledPrice  int64                  `protobuf:"varint,6,opt,name=settled_price,json=settledPrice,proto3" json:"settled_price,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_payment_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Transaction) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Transaction) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Transaction) GetSettledPrice() int64 {
	if x != nil {
		return x.SettledPrice
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Skip          uint64                 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_payment_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTransactionsRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ListTransactionsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListTransactionsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_payment_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type RefundRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentId      string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payment_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RefundResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProviderRefundId string                 `protobuf:"bytes,1,opt,name=provider_refund_id,json=providerRefundId,proto3" json:"provider_refund_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_payment_proto_rawDescGZIP(), []int{7}
}

func (x *RefundResponse) GetProviderRefundId() string {
	if x != nil {
		return x.ProviderRefundId
	}
	return ""
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_payment_proto_payment_proto protoreflect.FileDescriptor

const file_payment_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x1bpayment/proto/payment.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\"L\n" +
	"\x10CheckoutCartItem\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"\x86\x02\n" +
	"\x0fCheckoutRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vredirectURL\x18\x04 \x01(\tR\vredirectURL\x120\n" +
	"\bproducts\x18\x05 \x03(\v2\x14.pb.CheckoutCartItemR\bproducts\x12\x18\n" +
	"\aorderId\x18\x06 \x01(\x04R\aorderId\x12&\n" +
	"\x0ereservationIds\x18\a \x03(\tR\x0ereservationIds\x12\x1b\n" +
	"\tclient_ip\x18\b \x01(\tR\bclientIp\"v\n" +
	"\x15CustomerPortalRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01B\b\n" +
	"\x06_emailB\a\n" +
	"\x05_name\"\xea\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x03R\n" +
	"totalPrice\x12#\n" +
	"\rsettled_price\x18\x06 \x01(\x03R\fsettledPrice\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"t\n" +
	"\x17ListTransactionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x04 \x01(\x04R\x04take\"O\n" +
	"\x18ListTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"o\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"n\n" +
	"\x0eRefundResponse\x12,\n" +
	"\x12provider_refund_id\x18\x01 \x01(\tR\x10providerRefundId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount2\x8c\x03\n" +
	"\x0ePaymentService\x12L\n" +
	"\x15CreateCheckoutSession\x12\x13.pb.CheckoutRequest\x1a\x1c.google.protobuf.StringValue\"\x00\x12X\n" +
	"\x1bCreateCustomerPortalSession\x12\x19.pb.CustomerPortalRequest\x1a\x1c.google.protobuf.StringValue\"\x00\x12O\n" +
	"\x10ListTransactions\x12\x1b.pb.ListTransactionsRequest\x1a\x1c.pb.ListTransactionsResponse\"\x00\x128\n" +
	"\rRequestRefund\x12\x11.pb.RefundRequest\x1a\x12.pb.RefundResponse\"\x00\x12G\n" +
	"\x14ReconcileTransaction\x12\x1c.google.protobuf.StringValue\x1a\x0f.pb.Transaction\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_payment_proto_payment_proto_rawDescOnce sync.Once
	file_payment_proto_payment_proto_rawDescData []byte
)

func file_payment_proto_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_payment_proto_rawDesc), len(file_payment_proto_payment_proto_rawDesc)))
	})
	return file_payment_proto_payment_proto_rawDescData
}

var file_payment_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_payment_proto_goTypes = []any{
	(*CheckoutCartItem)(nil),         // 0: pb.CheckoutCartItem
	(*CheckoutRequest)(nil),          // 1: pb.CheckoutRequest
	(*CustomerPortalRequest)(nil),    // 2: pb.CustomerPortalRequest
	(*Transaction)(nil),              // 3: pb.Transaction
	(*ListTransactionsRequest)(nil),  // 4: pb.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 5: pb.ListTransactionsResponse
	(*RefundRequest)(nil),            // 6: pb.RefundRequest
	(*RefundResponse)(nil),           // 7: pb.RefundResponse
	(*wrapperspb.StringValue)(nil),   // 8: google.protobuf.StringValue
}
var file_payment_proto_payment_proto_depIdxs = []int32{
	0, // 0: pb.CheckoutRequest.products:type_name -> pb.CheckoutCartItem
	3, // 1: pb.ListTransactionsResponse.transactions:type_name -> pb.Transaction
	1, // 2: pb.PaymentService.CreateCheckoutSession:input_type -> pb.CheckoutRequest
	2, // 3: pb.PaymentService.CreateCustomerPortalSession:input_type -> pb.CustomerPortalRequest
	4, // 4: pb.PaymentService.ListTransactions:input_type -> pb.ListTransactionsRequest
	6, // 5: pb.PaymentService.RequestRefund:input_type -> pb.RefundRequest
	8, // 6: pb.PaymentService.ReconcileTransaction:input_type -> google.protobuf.StringValue
	8, // 7: pb.PaymentService.CreateCheckoutSession:output_type -> google.protobuf.StringValue
	8, // 8: pb.PaymentService.CreateCustomerPortalSession:output_type -> google.protobuf.StringValue
	5, // 9: pb.PaymentService.ListTransactions:output_type -> pb.ListTransactionsResponse
	7, // 10: pb.PaymentService.RequestRefund:output_type -> pb.RefundResponse
	3, // 11: pb.PaymentService.ReconcileTransaction:output_type -> pb.Transaction
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_payment_proto_init() }
func file_payment_proto_payment_proto_init() {
	if File_payment_proto_payment_proto != nil {
		return
	}
	file_payment_proto_payment_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_payment_proto_rawDesc), len(file_payment_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_payment_proto_msgTypes,
	}.Build()
	File_payment_proto_payment_proto = out.File
	file_payment_proto_payment_proto_goTypes = nil
	file_payment_proto_payment_proto_depIdxs = nil
}
