import { useEffect, useState } from 'react'
import { useCart } from './CartContext'
import { useNavigate, Link } from 'react-router-dom'
import { salePrice, vnd } from '../../shared/lib/format'

export function CartPage() {
  const { cart, expiresAt, loading, error, update, remove } = useCart(); const navigate = useNavigate(); const [remaining, setRemaining] = useState<number | null>(null); const total = cart.reduce((sum, line) => sum + salePrice(line.price, line.discountPercentage) * line.quantity, 0)
  useEffect(() => { if (!expiresAt) { setRemaining(null); return }; const tick = () => setRemaining(Math.max(0, Math.ceil((Date.parse(expiresAt) - Date.now()) / 1000))); tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer) }, [expiresAt])

  if (!cart.length) return <main className="state"><h1>Giỏ hàng của bạn đang trống</h1><p>Thêm sản phẩm để bắt đầu phiên giữ hàng khi bạn đăng nhập.</p><Link className="button" to="/">Khám phá sản phẩm</Link></main>
  return <main className="cart page-enter"><section><h1>Giỏ hàng</h1><p className="notice">Giỏ hàng và phiên giữ hàng đang được quản lý bởi GoshopX.</p>{remaining !== null && <p className="notice" role="status">Phiên giữ hàng còn {Math.floor(remaining / 60)} phút {remaining % 60} giây.</p>}{error && <p role="alert" className="error">{error}</p>}{cart.map(line => <article className="cart-line motion-card" key={line.id}><img src={line.thumbnail} alt=""/><div><b>{line.title}</b><p>{vnd(salePrice(line.price, line.discountPercentage))}</p><button className="remove-item" disabled={loading} aria-label={`Xóa ${line.title} khỏi giỏ hàng`} onClick={() => { void remove(String(line.id)).catch(() => undefined) }}>Xóa sản phẩm</button></div><div className="quantity"><button disabled={loading} onClick={() => void update(String(line.id), Math.max(1, line.quantity - 1))}>−</button><output>{line.quantity}</output><button disabled={loading} onClick={() => void update(String(line.id), Math.min(line.stock, line.quantity + 1))}>+</button></div></article>)}</section><aside className="summary"><h2>Tóm tắt đơn hàng</h2><p><span>Tạm tính</span><b>{vnd(total)}</b></p><p><span>Vận chuyển</span><span>Sẽ tính ở checkout</span></p><hr/><p className="total"><span>Tổng dự kiến</span><b>{vnd(total)}</b></p><Link className={`primary${loading || remaining === 0 ? ' disabled-link' : ''}`} aria-disabled={loading || remaining === 0} to={loading || remaining === 0 ? '/cart' : '/checkout'}>{loading ? 'Đang kiểm tra…' : remaining === 0 ? 'Phiên giữ hàng đã hết hạn' : 'Thanh toán an toàn'}</Link><button className="button secondary-action" onClick={() => navigate('/')}>Tiếp tục mua sắm</button></aside></main>
}
